# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CPY-ZitQatq.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 400)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(400, 400))
        MainWindow.setMaximumSize(QSize(400, 400))
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setIconSize(QSize(24, 24))
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks|QMainWindow.ForceTabbedDocks|QMainWindow.GroupedDragging|QMainWindow.VerticalTabs)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMaximumSize(QSize(400, 400))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 400, 400))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QSize(385, 0))
        self.tabWidget.setMaximumSize(QSize(400, 400))
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabCPU = QWidget()
        self.tabCPU.setObjectName(u"tabCPU")
        self.tabCPU.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tabCPU.sizePolicy().hasHeightForWidth())
        self.tabCPU.setSizePolicy(sizePolicy2)
        self.tabCPU.setMaximumSize(QSize(400, 400))
        self.boxProcessor = QGroupBox(self.tabCPU)
        self.boxProcessor.setObjectName(u"boxProcessor")
        self.boxProcessor.setEnabled(True)
        self.boxProcessor.setGeometry(QRect(10, 0, 371, 232))
        sizePolicy1.setHeightForWidth(self.boxProcessor.sizePolicy().hasHeightForWidth())
        self.boxProcessor.setSizePolicy(sizePolicy1)
        self.boxProcessor.setMinimumSize(QSize(0, 223))
        self.boxProcessor.setMaximumSize(QSize(400, 400))
        self.label_Specification = QLabel(self.boxProcessor)
        self.label_Specification.setObjectName(u"label_Specification")
        self.label_Specification.setGeometry(QRect(2, 105, 70, 16))
        sizePolicy.setHeightForWidth(self.label_Specification.sizePolicy().hasHeightForWidth())
        self.label_Specification.setSizePolicy(sizePolicy)
        self.label_Specification.setScaledContents(True)
        self.lineEdit_Name = QLineEdit(self.boxProcessor)
        self.lineEdit_Name.setObjectName(u"lineEdit_Name")
        self.lineEdit_Name.setEnabled(True)
        self.lineEdit_Name.setGeometry(QRect(72, 20, 191, 18))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.lineEdit_Name.sizePolicy().hasHeightForWidth())
        self.lineEdit_Name.setSizePolicy(sizePolicy3)
        self.lineEdit_Name.setFrame(True)
        self.lineEdit_Name.setAlignment(Qt.AlignCenter)
        self.lineEdit_Name.setDragEnabled(False)
        self.lineEdit_Name.setReadOnly(True)
        self.label_Name = QLabel(self.boxProcessor)
        self.label_Name.setObjectName(u"label_Name")
        self.label_Name.setGeometry(QRect(35, 20, 41, 16))
        sizePolicy.setHeightForWidth(self.label_Name.sizePolicy().hasHeightForWidth())
        self.label_Name.setSizePolicy(sizePolicy)
        self.label_Name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_Specification = QLineEdit(self.boxProcessor)
        self.lineEdit_Specification.setObjectName(u"lineEdit_Specification")
        self.lineEdit_Specification.setEnabled(True)
        self.lineEdit_Specification.setGeometry(QRect(70, 105, 291, 18))
        sizePolicy3.setHeightForWidth(self.lineEdit_Specification.sizePolicy().hasHeightForWidth())
        self.lineEdit_Specification.setSizePolicy(sizePolicy3)
        self.lineEdit_Specification.setMouseTracking(True)
        self.lineEdit_Specification.setLayoutDirection(Qt.LeftToRight)
        self.lineEdit_Specification.setAlignment(Qt.AlignCenter)
        self.lineEdit_Specification.setDragEnabled(False)
        self.lineEdit_Specification.setReadOnly(True)
        self.graphicsView = QGraphicsView(self.boxProcessor)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setEnabled(False)
        self.graphicsView.setGeometry(QRect(272, 15, 85, 85))
        sizePolicy1.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy1)
        self.graphicsView.setMinimumSize(QSize(85, 85))
        self.graphicsView.setMaximumSize(QSize(85, 85))
        self.graphicsView.setFocusPolicy(Qt.NoFocus)
        self.graphicsView.setLayoutDirection(Qt.RightToLeft)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QFrame.Sunken)
        self.graphicsView.setLineWidth(0)
        self.graphicsView.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.Dense7Pattern)
        self.graphicsView.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.Dense7Pattern)
        self.graphicsView.setForegroundBrush(brush1)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.lineEdit_Max_TDP = QLineEdit(self.boxProcessor)
        self.lineEdit_Max_TDP.setObjectName(u"lineEdit_Max_TDP")
        self.lineEdit_Max_TDP.setEnabled(True)
        self.lineEdit_Max_TDP.setGeometry(QRect(212, 40, 51, 18))
        self.lineEdit_Max_TDP.setAlignment(Qt.AlignCenter)
        self.lineEdit_Max_TDP.setReadOnly(True)
        self.label_Max_TDP = QLabel(self.boxProcessor)
        self.label_Max_TDP.setObjectName(u"label_Max_TDP")
        self.label_Max_TDP.setEnabled(True)
        self.label_Max_TDP.setGeometry(QRect(162, 40, 49, 16))
        self.label_Max_TDP.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.label_Max_TDP.setWordWrap(False)
        self.lineEdit_Codename = QLineEdit(self.boxProcessor)
        self.lineEdit_Codename.setObjectName(u"lineEdit_Codename")
        self.lineEdit_Codename.setEnabled(True)
        self.lineEdit_Codename.setGeometry(QRect(72, 40, 87, 18))
        self.lineEdit_Codename.setAlignment(Qt.AlignCenter)
        self.lineEdit_Codename.setReadOnly(True)
        self.label_Codename = QLabel(self.boxProcessor)
        self.label_Codename.setObjectName(u"label_Codename")
        self.label_Codename.setGeometry(QRect(4, 40, 64, 16))
        self.lineEdit_Package_Socket = QLineEdit(self.boxProcessor)
        self.lineEdit_Package_Socket.setObjectName(u"lineEdit_Package_Socket")
        self.lineEdit_Package_Socket.setEnabled(True)
        self.lineEdit_Package_Socket.setGeometry(QRect(72, 60, 191, 18))
        self.lineEdit_Package_Socket.setAlignment(Qt.AlignCenter)
        self.lineEdit_Package_Socket.setReadOnly(True)
        self.label_Package = QLabel(self.boxProcessor)
        self.label_Package.setObjectName(u"label_Package")
        self.label_Package.setGeometry(QRect(23, 60, 49, 16))
        self.lineEdit_Core_Voltage = QLineEdit(self.boxProcessor)
        self.lineEdit_Core_Voltage.setObjectName(u"lineEdit_Core_Voltage")
        self.lineEdit_Core_Voltage.setEnabled(True)
        self.lineEdit_Core_Voltage.setGeometry(QRect(212, 80, 51, 18))
        self.lineEdit_Core_Voltage.setAlignment(Qt.AlignCenter)
        self.lineEdit_Core_Voltage.setReadOnly(True)
        self.label_Core_Voltage = QLabel(self.boxProcessor)
        self.label_Core_Voltage.setObjectName(u"label_Core_Voltage")
        self.label_Core_Voltage.setGeometry(QRect(137, 80, 71, 16))
        self.label_Core_Voltage.setAlignment(Qt.AlignCenter)
        self.lineEdit_Nanometer = QLineEdit(self.boxProcessor)
        self.lineEdit_Nanometer.setObjectName(u"lineEdit_Nanometer")
        self.lineEdit_Nanometer.setEnabled(True)
        self.lineEdit_Nanometer.setGeometry(QRect(72, 80, 62, 18))
        self.lineEdit_Nanometer.setCursorPosition(0)
        self.lineEdit_Nanometer.setAlignment(Qt.AlignCenter)
        self.lineEdit_Nanometer.setReadOnly(True)
        self.label_Tecnology = QLabel(self.boxProcessor)
        self.label_Tecnology.setObjectName(u"label_Tecnology")
        self.label_Tecnology.setGeometry(QRect(13, 80, 54, 16))
        self.label_Tecnology.setAlignment(Qt.AlignCenter)
        self.label_Family = QLabel(self.boxProcessor)
        self.label_Family.setObjectName(u"label_Family")
        self.label_Family.setGeometry(QRect(33, 130, 36, 16))
        self.lineEdit_Family = QLineEdit(self.boxProcessor)
        self.lineEdit_Family.setObjectName(u"lineEdit_Family")
        self.lineEdit_Family.setEnabled(True)
        self.lineEdit_Family.setGeometry(QRect(72, 130, 60, 18))
        self.lineEdit_Family.setAlignment(Qt.AlignCenter)
        self.lineEdit_Family.setReadOnly(True)
        self.label_Model = QLabel(self.boxProcessor)
        self.label_Model.setObjectName(u"label_Model")
        self.label_Model.setGeometry(QRect(143, 130, 39, 16))
        self.lineEdit_Model = QLineEdit(self.boxProcessor)
        self.lineEdit_Model.setObjectName(u"lineEdit_Model")
        self.lineEdit_Model.setEnabled(True)
        self.lineEdit_Model.setGeometry(QRect(180, 130, 51, 18))
        self.lineEdit_Model.setAlignment(Qt.AlignCenter)
        self.lineEdit_Model.setReadOnly(True)
        self.label_Stepping = QLabel(self.boxProcessor)
        self.label_Stepping.setObjectName(u"label_Stepping")
        self.label_Stepping.setGeometry(QRect(250, 130, 49, 16))
        self.label_Stepping.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_Stepping = QLineEdit(self.boxProcessor)
        self.lineEdit_Stepping.setObjectName(u"lineEdit_Stepping")
        self.lineEdit_Stepping.setEnabled(True)
        self.lineEdit_Stepping.setGeometry(QRect(300, 130, 61, 18))
        self.lineEdit_Stepping.setAlignment(Qt.AlignCenter)
        self.lineEdit_Stepping.setReadOnly(True)
        self.label_ExtFamily = QLabel(self.boxProcessor)
        self.label_ExtFamily.setObjectName(u"label_ExtFamily")
        self.label_ExtFamily.setGeometry(QRect(11, 150, 61, 16))
        self.lineEdit_ExtFamily = QLineEdit(self.boxProcessor)
        self.lineEdit_ExtFamily.setObjectName(u"lineEdit_ExtFamily")
        self.lineEdit_ExtFamily.setEnabled(True)
        self.lineEdit_ExtFamily.setGeometry(QRect(72, 150, 46, 18))
        self.lineEdit_ExtFamily.setAlignment(Qt.AlignCenter)
        self.lineEdit_ExtFamily.setReadOnly(True)
        self.label_ExtModel = QLabel(self.boxProcessor)
        self.label_ExtModel.setObjectName(u"label_ExtModel")
        self.label_ExtModel.setGeometry(QRect(120, 150, 57, 16))
        self.lineEdit_ExtModel = QLineEdit(self.boxProcessor)
        self.lineEdit_ExtModel.setObjectName(u"lineEdit_ExtModel")
        self.lineEdit_ExtModel.setEnabled(True)
        self.lineEdit_ExtModel.setGeometry(QRect(180, 150, 51, 18))
        self.lineEdit_ExtModel.setAlignment(Qt.AlignCenter)
        self.lineEdit_ExtModel.setReadOnly(True)
        self.label_Revision = QLabel(self.boxProcessor)
        self.label_Revision.setObjectName(u"label_Revision")
        self.label_Revision.setGeometry(QRect(250, 150, 49, 16))
        self.label_Revision.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_Revision = QLineEdit(self.boxProcessor)
        self.lineEdit_Revision.setObjectName(u"lineEdit_Revision")
        self.lineEdit_Revision.setEnabled(True)
        self.lineEdit_Revision.setGeometry(QRect(300, 150, 61, 18))
        self.lineEdit_Revision.setAlignment(Qt.AlignCenter)
        self.lineEdit_Revision.setReadOnly(True)
        self.label_Instructions = QLabel(self.boxProcessor)
        self.label_Instructions.setObjectName(u"label_Instructions")
        self.label_Instructions.setGeometry(QRect(5, 170, 65, 16))
        self.textEdit = QTextEdit(self.boxProcessor)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QRect(70, 170, 291, 51))
        font = QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setKerning(True)
        self.textEdit.setFont(font)
        self.textEdit.setContextMenuPolicy(Qt.NoContextMenu)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setFrameShape(QFrame.StyledPanel)
        self.textEdit.setFrameShadow(QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setMidLineWidth(0)
        self.textEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.textEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.textEdit.setAutoFormatting(QTextEdit.AutoAll)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setLineWrapMode(QTextEdit.WidgetWidth)
        self.textEdit.setLineWrapColumnOrWidth(0)
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setTextInteractionFlags(Qt.NoTextInteraction)
        self.boxClocks = QGroupBox(self.tabCPU)
        self.boxClocks.setObjectName(u"boxClocks")
        self.boxClocks.setGeometry(QRect(10, 240, 180, 110))
        sizePolicy4 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.boxClocks.sizePolicy().hasHeightForWidth())
        self.boxClocks.setSizePolicy(sizePolicy4)
        self.boxClocks.setMinimumSize(QSize(0, 0))
        self.boxClocks.setMaximumSize(QSize(180, 110))
        self.label_CoreSpeed = QLabel(self.boxClocks)
        self.label_CoreSpeed.setObjectName(u"label_CoreSpeed")
        self.label_CoreSpeed.setGeometry(QRect(7, 20, 60, 16))
        sizePolicy.setHeightForWidth(self.label_CoreSpeed.sizePolicy().hasHeightForWidth())
        self.label_CoreSpeed.setSizePolicy(sizePolicy)
        self.label_CoreSpeed.setMinimumSize(QSize(0, 0))
        self.label_CoreSpeed.setMaximumSize(QSize(99, 99))
        self.label_CoreSpeed.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_CoreSpeed = QLineEdit(self.boxClocks)
        self.lineEdit_CoreSpeed.setObjectName(u"lineEdit_CoreSpeed")
        self.lineEdit_CoreSpeed.setEnabled(True)
        self.lineEdit_CoreSpeed.setGeometry(QRect(70, 20, 100, 18))
        self.lineEdit_CoreSpeed.setAlignment(Qt.AlignCenter)
        self.lineEdit_CoreSpeed.setReadOnly(True)
        self.lineEdit_Multiplier = QLineEdit(self.boxClocks)
        self.lineEdit_Multiplier.setObjectName(u"lineEdit_Multiplier")
        self.lineEdit_Multiplier.setGeometry(QRect(70, 40, 100, 18))
        self.lineEdit_Multiplier.setAlignment(Qt.AlignCenter)
        self.lineEdit_Multiplier.setReadOnly(True)
        self.lineEdit_BUSSpeed = QLineEdit(self.boxClocks)
        self.lineEdit_BUSSpeed.setObjectName(u"lineEdit_BUSSpeed")
        self.lineEdit_BUSSpeed.setGeometry(QRect(70, 60, 100, 18))
        self.lineEdit_BUSSpeed.setAlignment(Qt.AlignCenter)
        self.lineEdit_BUSSpeed.setReadOnly(True)
        self.lineEdit_RatedFSB = QLineEdit(self.boxClocks)
        self.lineEdit_RatedFSB.setObjectName(u"lineEdit_RatedFSB")
        self.lineEdit_RatedFSB.setGeometry(QRect(70, 80, 100, 18))
        self.lineEdit_RatedFSB.setAlignment(Qt.AlignCenter)
        self.lineEdit_RatedFSB.setReadOnly(True)
        self.label_Multiplier = QLabel(self.boxClocks)
        self.label_Multiplier.setObjectName(u"label_Multiplier")
        self.label_Multiplier.setGeometry(QRect(9, 40, 57, 16))
        self.label_Multiplier.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_BUSSpeed = QLabel(self.boxClocks)
        self.label_BUSSpeed.setObjectName(u"label_BUSSpeed")
        self.label_BUSSpeed.setGeometry(QRect(9, 60, 57, 16))
        self.label_BUSSpeed.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_RatedFSB = QLabel(self.boxClocks)
        self.label_RatedFSB.setObjectName(u"label_RatedFSB")
        self.label_RatedFSB.setGeometry(QRect(9, 80, 57, 16))
        self.label_RatedFSB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.boxCache = QGroupBox(self.tabCPU)
        self.boxCache.setObjectName(u"boxCache")
        self.boxCache.setGeometry(QRect(200, 240, 180, 110))
        self.label_L1Data = QLabel(self.boxCache)
        self.label_L1Data.setObjectName(u"label_L1Data")
        self.label_L1Data.setGeometry(QRect(10, 20, 49, 16))
        self.lineEdit_L1Data = QLineEdit(self.boxCache)
        self.lineEdit_L1Data.setObjectName(u"lineEdit_L1Data")
        self.lineEdit_L1Data.setGeometry(QRect(60, 20, 100, 18))
        self.lineEdit_L1Data.setAlignment(Qt.AlignCenter)
        self.lineEdit_L1Data.setReadOnly(True)
        self.label_L1Inst = QLabel(self.boxCache)
        self.label_L1Inst.setObjectName(u"label_L1Inst")
        self.label_L1Inst.setGeometry(QRect(10, 40, 49, 16))
        self.lineEdit_L1Inst = QLineEdit(self.boxCache)
        self.lineEdit_L1Inst.setObjectName(u"lineEdit_L1Inst")
        self.lineEdit_L1Inst.setGeometry(QRect(60, 40, 100, 18))
        self.lineEdit_L1Inst.setAlignment(Qt.AlignCenter)
        self.lineEdit_L1Inst.setReadOnly(True)
        self.lineEdit_L2 = QLineEdit(self.boxCache)
        self.lineEdit_L2.setObjectName(u"lineEdit_L2")
        self.lineEdit_L2.setGeometry(QRect(60, 60, 100, 18))
        self.lineEdit_L2.setAlignment(Qt.AlignCenter)
        self.lineEdit_L2.setReadOnly(True)
        self.lineEdit_L3 = QLineEdit(self.boxCache)
        self.lineEdit_L3.setObjectName(u"lineEdit_L3")
        self.lineEdit_L3.setGeometry(QRect(60, 80, 100, 18))
        self.lineEdit_L3.setAlignment(Qt.AlignCenter)
        self.lineEdit_L3.setReadOnly(True)
        self.label_L2 = QLabel(self.boxCache)
        self.label_L2.setObjectName(u"label_L2")
        self.label_L2.setGeometry(QRect(10, 60, 49, 16))
        self.label_L3 = QLabel(self.boxCache)
        self.label_L3.setObjectName(u"label_L3")
        self.label_L3.setGeometry(QRect(10, 80, 49, 16))
        self.tabWidget.addTab(self.tabCPU, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CPY-Z", None))
        self.boxProcessor.setTitle(QCoreApplication.translate("MainWindow", u"Processor", None))
        self.label_Specification.setText(QCoreApplication.translate("MainWindow", u"Specification", None))
        self.lineEdit_Name.setPlaceholderText("")
        self.label_Name.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.lineEdit_Specification.setPlaceholderText("")
        self.lineEdit_Max_TDP.setPlaceholderText("")
        self.label_Max_TDP.setText(QCoreApplication.translate("MainWindow", u"Max TDP", None))
        self.lineEdit_Codename.setPlaceholderText("")
        self.label_Codename.setText(QCoreApplication.translate("MainWindow", u"Code Name", None))
        self.lineEdit_Package_Socket.setPlaceholderText("")
        self.label_Package.setText(QCoreApplication.translate("MainWindow", u"Package", None))
        self.lineEdit_Core_Voltage.setPlaceholderText("")
        self.label_Core_Voltage.setText(QCoreApplication.translate("MainWindow", u"Core Voltage", None))
        self.lineEdit_Nanometer.setPlaceholderText("")
        self.label_Tecnology.setText(QCoreApplication.translate("MainWindow", u"Tecnology", None))
        self.label_Family.setText(QCoreApplication.translate("MainWindow", u"Family", None))
        self.lineEdit_Family.setPlaceholderText("")
        self.label_Model.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.lineEdit_Model.setPlaceholderText("")
        self.label_Stepping.setText(QCoreApplication.translate("MainWindow", u"Stepping", None))
        self.lineEdit_Stepping.setPlaceholderText("")
        self.label_ExtFamily.setText(QCoreApplication.translate("MainWindow", u"Ext. Family", None))
        self.label_ExtModel.setText(QCoreApplication.translate("MainWindow", u"Ext. Model", None))
        self.label_Revision.setText(QCoreApplication.translate("MainWindow", u"Revision", None))
        self.label_Instructions.setText(QCoreApplication.translate("MainWindow", u"Instructions", None))
        self.textEdit.setPlaceholderText("")
        self.boxClocks.setTitle(QCoreApplication.translate("MainWindow", u"Clocks (Core #0)", None))
        self.label_CoreSpeed.setText(QCoreApplication.translate("MainWindow", u"Core Speed", None))
        self.label_Multiplier.setText(QCoreApplication.translate("MainWindow", u"Multiplier", None))
        self.label_BUSSpeed.setText(QCoreApplication.translate("MainWindow", u"Bus Speed", None))
        self.label_RatedFSB.setText(QCoreApplication.translate("MainWindow", u"Rated FSB", None))
        self.boxCache.setTitle(QCoreApplication.translate("MainWindow", u"Cache", None))
        self.label_L1Data.setText(QCoreApplication.translate("MainWindow", u"L1 Data", None))
        self.label_L1Inst.setText(QCoreApplication.translate("MainWindow", u"L1 Inst.", None))
        self.label_L2.setText(QCoreApplication.translate("MainWindow", u"Level 2", None))
        self.label_L3.setText(QCoreApplication.translate("MainWindow", u"Level 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCPU), QCoreApplication.translate("MainWindow", u"CPU", None))
    # retranslateUi

